[package]
name = "warpack-lua-parser"
description = "A Lua parser library used by Warpack."
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
pest = "2.5.4"
pest_derive = "2.5.4"
