[package]
name = "warpack-formats"
description = "A library containing tools to work with various Warcraft III file formats used by Warpack."
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true


[dependencies]

# util
lazy_static = "1.4.0"
atoi = "0.3.2"
indexmap = "1.3.2"
slotmap = { version = "0.4.0", features = ["serde"] }
num-traits = "0.2.11"
bitflags = "1.2.1"

# parsing/casting
byteorder = "1.3.4"
byte-slice-cast = "0.3.5"
serde = { version = "1.0.104", features = ["derive", "rc"] }

# lua
rlua = "0.16.3"

# error handling
thiserror = "1.0.11"
anyhow = "1.0.26"
